(() => {
  'use strict';
  const AUTOPLAY_KEY='pure_ddz_qily_autoplay_v1',VISUAL_HOLD_MS=900;
  let autoplay=localStorage.getItem(AUTOPLAY_KEY)==='1',previousState=null,managedTurnToken='',autoplayTimer=null,stageSignature='',stageBusy=false,stageTimer=null;
  const visualQueue=[],queuedSignatures=new Set(),$=id=>document.getElementById(id),sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  function isTouchMobile(){return (navigator.maxTouchPoints||0)>0&&window.matchMedia('(max-width:1180px)').matches}
  function playSignature(play){return !play?.cards?.length?'':`${play.player}|${play.combo?.type||''}|${play.cards.map(card=>card.id).join('-')}`}
  function snapshotPlay(play){return {player:play.player,combo:{...(play.combo||{})},cards:play.cards.map(card=>({...card}))}}
  function ensureVisualStage(){const table=document.querySelector('.table-wrap');if(!table)return;if(!$('v120-play-stage')){const stage=document.createElement('div');stage.id='v120-play-stage';stage.className='v120-play-stage';stage.setAttribute('aria-live','assertive');stage.setAttribute('aria-label','本次出牌视觉反馈');table.appendChild(stage)}if(!$('v120-pass-flash')){const bubble=document.createElement('div');bubble.id='v120-pass-flash';bubble.className='v120-pass-flash';table.appendChild(bubble)}}
  function ensureOrientationNotice(){if($('v120-orientation-notice'))return;const notice=document.createElement('div');notice.id='v120-orientation-notice';notice.className='v120-orientation-notice';notice.innerHTML='<div class="v120-orientation-card"><b>横屏牌桌 · 可视化优先</b><p>手机/平板使用横屏可获得更大的扑克牌与更清晰的出牌反馈。点击下方按钮尝试进入横屏牌桌；若浏览器不允许自动旋转，请将设备旋转为横屏。</p><button id="v120-landscape-now" type="button">进入横屏牌桌</button></div>';document.body.appendChild(notice);$('v120-landscape-now').addEventListener('click',requestLandscape)}
  function updateOrientationNotice(){ensureOrientationNotice();const notice=$('v120-orientation-notice');if(!notice)return;notice.classList.toggle('show',isTouchMobile()&&window.matchMedia('(orientation:portrait)').matches)}
  async function requestLandscape(){if(!isTouchMobile())return false;try{if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen({navigationUI:'hide'}).catch(()=>{});if(screen.orientation?.lock){await screen.orientation.lock('landscape');updateOrientationNotice();return true}}catch(_error){}updateOrientationNotice();return false}
  function playerName(player){return player===0?'我':player===1?'左家 · 电脑':'右家 · 电脑'}
  function renderLargeCard(card){return window.QilyLeanCardTheme?.renderCard?`<span class="v120-play-card">${window.QilyLeanCardTheme.renderCard(card)}</span>`:`<span class="v120-play-card">${String(card.rank)}</span>`}
  function renderStage(play){ensureVisualStage();const stage=$('v120-play-stage');if(!stage)return;stageSignature=playSignature(play);const combo=play.combo?.type||'出牌',comboText={single:'单牌',pair:'对子',triple:'三张',triple1:'三带一',triple2:'三带二',straight:'顺子',pairStraight:'连对',airplane:'飞机',airplane1:'飞机带单',airplane2:'飞机带对',four2:'四带二',four2pair:'四带两对',bomb:'炸弹',rocket:'王炸'}[combo]||'出牌';stage.classList.remove('show','is-bomb');void stage.offsetWidth;stage.innerHTML=`<div class="v120-play-owner">${playerName(play.player)} · ${comboText} · ${play.cards.length} 张</div><div class="v120-play-cards">${play.cards.map(renderLargeCard).join('')}</div>`;stage.classList.toggle('is-bomb',['bomb','rocket'].includes(combo));stage.classList.add('show');stageBusy=true;if(stageTimer)clearTimeout(stageTimer);stageTimer=setTimeout(()=>{stageBusy=false;stageTimer=null;processVisualQueue()},VISUAL_HOLD_MS)}
  function processVisualQueue(){if(stageBusy||!visualQueue.length)return;const play=visualQueue.shift();queuedSignatures.delete(playSignature(play));renderStage(play)}
  function showPlay(play){if(!play?.cards?.length)return;const signature=playSignature(play);if(signature===stageSignature||queuedSignatures.has(signature))return;const copy=snapshotPlay(play);visualQueue.push(copy);queuedSignatures.add(signature);processVisualQueue()}
  function clearPlayStage(force=false){if(!force&&(stageBusy||visualQueue.length))return;const stage=$('v120-play-stage');if(stage){stage.classList.remove('show','is-bomb');stage.innerHTML=''}stageSignature='';if(force){visualQueue.length=0;queuedSignatures.clear();stageBusy=false;if(stageTimer){clearTimeout(stageTimer);stageTimer=null}}}
  function showPass(player){ensureVisualStage();const bubble=$('v120-pass-flash');if(!bubble)return;bubble.className=`v120-pass-flash ${player===0?'me':player===1?'left':'right'}`;bubble.textContent=`${playerName(player)} · 不要`;void bubble.offsetWidth;bubble.classList.add('show');setTimeout(()=>bubble.classList.remove('show'),920)}
  function ensureAutoplayControl(){const old=$('hint');if(!old)return null;if(old.dataset.qilyAutoplay==='1')return old;const button=old.cloneNode(true);button.id='hint';button.dataset.qilyAutoplay='1';button.classList.add('autoplay-btn');old.replaceWith(button);button.addEventListener('click',()=>setAutoplay(!autoplay,true));return button}
  function ensureSettingsToggle(){const grid=document.querySelector('.settings-grid');if(!grid||$('setting-qily-autoplay'))return;const row=document.createElement('label');row.className='setting-row';row.innerHTML='<span><b>启力托管</b><small>默认关闭，关闭时完全自主判断；开启后由启力 AI 自动叫分和出牌。</small></span><input id="setting-qily-autoplay" type="checkbox">';const difficulty=grid.querySelector('.setting-select:last-of-type');grid.insertBefore(row,difficulty||null);$('setting-qily-autoplay').addEventListener('change',event=>setAutoplay(event.target.checked,true))}
  function normalizeCopy(){const help=$('help-modal');if(help){const eyebrow=help.querySelector('.eyebrow');if(eyebrow)eyebrow.textContent='自主思考优先，托管按需开启';const ai=[...help.querySelectorAll('.help-sections section')].find(section=>section.querySelector('b')?.textContent.trim()==='AI');if(ai){const title=ai.querySelector('h3'),copy=ai.querySelector('p');if(title)title.textContent='启力托管';if(copy)copy.textContent='默认关闭，由你自主判断和出牌；需要休息时可开启启力托管，由启力 AI 自动叫分、选牌与出牌。'}}const hint=$('hint-message');if(hint)hint.textContent='自主判断后点“出牌”；需要休息时可开启“启力托管”。'}
  function setAutoplay(next,announce=false){autoplay=Boolean(next);localStorage.setItem(AUTOPLAY_KEY,autoplay?'1':'0');managedTurnToken='';if(autoplayTimer){clearTimeout(autoplayTimer);autoplayTimer=null}updateAutoplayUi();if(announce){const toast=$('toast');if(toast){toast.textContent=autoplay?'启力托管已开启：自动叫分与出牌':'启力托管已关闭：现在由你自主判断出牌';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1700)}}}
  function updateAutoplayUi(){const button=ensureAutoplayControl();if(button){button.textContent=`启力托管：${autoplay?'开':'关'}`;button.classList.toggle('on',autoplay);button.setAttribute('aria-pressed',String(autoplay));button.title=autoplay?'点击关闭托管，恢复自主出牌':'点击开启托管，由启力 AI 自动出牌'}const setting=$('setting-qily-autoplay');if(setting)setting.checked=autoplay;const play=$('play');if(play)play.textContent='出牌'}
  function currentTurnToken(state){return `${state.roundNumber}|${state.phase}|${state.current}|${state.hands?.[0]?.length||0}|${state.bidTurns||0}|${playSignature(state.lastPlay)}`}
  function scheduleAutoplay(state){if(!autoplay||state.current!==0||!['bidding','playing'].includes(state.phase)||stageBusy||visualQueue.length)return;const token=currentTurnToken(state);if(token===managedTurnToken||autoplayTimer)return;managedTurnToken=token;autoplayTimer=setTimeout(async()=>{autoplayTimer=null;if(!autoplay||!window.PureDDZTest)return;const fresh=window.PureDDZTest.getState();if(currentTurnToken(fresh)!==token||fresh.current!==0)return;try{if(fresh.phase==='bidding'){const bid=window.PureDDZTest.chooseAiBid(0),button=document.querySelector(`[data-bid="${bid}"]`);if(button&&!button.disabled)button.click();else managedTurnToken='';return}const choice=window.PureDDZTest.chooseAiPlay(0);if(!choice?.cards?.length){const pass=$('pass');if(pass&&!pass.disabled)pass.click();else managedTurnToken='';return}choice.cards.forEach(card=>{const button=document.querySelector(`#hand .card[data-id="${card.id}"]`);if(button&&!button.classList.contains('selected'))button.click()});await sleep(80);const play=$('play');if(play&&!play.disabled)play.click();else managedTurnToken=''}catch(_error){managedTurnToken=''}},620)}
  function detectPass(prev,next){if(!prev||prev.phase!=='playing'||next.phase!=='playing'||prev.current===next.current)return;const beforeSig=playSignature(prev.lastPlay),afterSig=playSignature(next.lastPlay);if(beforeSig===afterSig&&beforeSig){showPass(prev.current);return}if(beforeSig&&!afterSig&&next.current===prev.lastPlay?.player)showPass(prev.current)}
  function refresh(){if(!window.PureDDZTest)return;ensureVisualStage();ensureSettingsToggle();normalizeCopy();updateAutoplayUi();updateOrientationNotice();const state=window.PureDDZTest.getState();detectPass(previousState,state);const signature=playSignature(state.lastPlay);if(signature)showPlay(state.lastPlay);else if(state.phase!=='bidding')clearPlayStage();scheduleAutoplay(state);previousState=state}
  function start(){ensureVisualStage();ensureOrientationNotice();ensureSettingsToggle();normalizeCopy();updateAutoplayUi();updateOrientationNotice();window.addEventListener('orientationchange',()=>setTimeout(updateOrientationNotice,160));window.addEventListener('resize',updateOrientationNotice);['welcome-start','start','again'].forEach(id=>$(id)?.addEventListener('click',()=>{if(isTouchMobile())requestLandscape()},{passive:true}));document.addEventListener('pointerdown',()=>{if(isTouchMobile()&&window.matchMedia('(orientation:portrait)').matches)requestLandscape()},{once:true,passive:true});setInterval(refresh,120)}
  window.QilyLeanV120=Object.freeze({version:'1.2.0',visualHoldMs:VISUAL_HOLD_MS,get autoplay(){return autoplay},setAutoplay,requestLandscape,refresh});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
