/* QilyLean Global Knowledge Fixed Bottom Dock V1｜2026-09-16
 * Mirrors the international-site seven-action fixed-bottom navigation layout,
 * but keeps every action inside the non-commercial Global Knowledge boundary.
 */
(function(d,w){'use strict';
if(w.__qilyGlobalKnowledgeDockV1)return;w.__qilyGlobalKnowledgeDockV1=true;
var ORDER=['home','top','back','previous','search','current','library'];
var LABELS={home:['首页'],top:['顶部'],back:['上一层级'],previous:['上一网页'],search:['本站搜索'],current:['分享当前'],library:['知识目录']};
var MOBILE_LABELS={home:['首页'],top:['顶部'],back:['上一','层级'],previous:['上一','网页'],search:['本站','搜索'],current:['分享','当前'],library:['知识','目录']};
function style(){if(d.getElementById('qilyGlobalKnowledgeDockV1Style'))return;var s=d.createElement('style');s.id='qilyGlobalKnowledgeDockV1Style';s.textContent=[
':root{--qily-gk-dock-shell:rgba(255,255,255,.98);--qily-gk-dock-normal:#0f4b5a;--qily-gk-dock-hover:#073c47;--qily-gk-dock-line:#d5e4e3;--qily-gk-dock-gold:#caa15f;--qily-gk-dock-text:#fff;--qily-gk-dock-active-text:#ffe39b;--qily-gk-dock-gap:4px}',
'html:root body #floatDock.qily-page-action-nav{position:fixed!important;left:50%!important;right:auto!important;top:auto!important;bottom:12px!important;z-index:2147482000!important;display:grid!important;grid-template-columns:repeat(7,minmax(0,1fr))!important;align-items:stretch!important;box-sizing:border-box!important;width:min(1180px,calc(100% - 36px))!important;max-width:1180px!important;height:auto!important;gap:var(--qily-gk-dock-gap)!important;margin:0!important;padding:6px!important;border:1px solid var(--qily-gk-dock-line)!important;border-radius:10px!important;background:var(--qily-gk-dock-shell)!important;box-shadow:0 -8px 28px rgba(15,75,90,.16)!important;overflow:hidden!important;transform:translateX(-50%)!important;backdrop-filter:blur(10px)!important;-webkit-backdrop-filter:blur(10px)!important;touch-action:pan-y pinch-zoom!important}',
'html:root body #floatDock.qily-page-action-nav .qily-float-btn{display:flex!important;align-items:center!important;justify-content:center!important;box-sizing:border-box!important;width:100%!important;min-width:0!important;min-height:52px!important;margin:0!important;padding:9px 6px!important;border:1px solid var(--qily-gk-dock-normal)!important;border-radius:8px!important;color:var(--qily-gk-dock-text)!important;-webkit-text-fill-color:var(--qily-gk-dock-text)!important;background:var(--qily-gk-dock-normal)!important;box-shadow:0 3px 10px rgba(7,60,71,.12)!important;font:850 14px/1.2 "Microsoft YaHei","PingFang SC",Arial,sans-serif!important;text-align:center!important;white-space:normal!important;cursor:pointer!important;appearance:none!important;-webkit-appearance:none!important;touch-action:manipulation!important;transition:background-color .16s ease,border-color .16s ease,box-shadow .16s ease,color .16s ease,transform .12s ease!important}',
'html:root body #floatDock .qily-dock-label{display:block!important;width:100%!important;color:inherit!important;-webkit-text-fill-color:inherit!important;font:inherit!important;line-height:1.15!important;text-align:center!important;pointer-events:none!important}',
'html:root body #floatDock .qily-dock-label>span{display:inline!important;color:inherit!important;-webkit-text-fill-color:inherit!important}',
'html:root body #floatDock .qily-float-btn:hover,html:root body #floatDock .qily-float-btn:focus-visible{color:#fff!important;-webkit-text-fill-color:#fff!important;background:var(--qily-gk-dock-hover)!important;border-color:var(--qily-gk-dock-gold)!important;box-shadow:inset 0 0 0 2px rgba(202,161,95,.55)!important,0 7px 16px rgba(7,60,71,.22)!important;outline:none!important;transform:translateY(-1px)!important}',
'html:root body #floatDock .qily-float-btn:active{color:var(--qily-gk-dock-active-text)!important;-webkit-text-fill-color:var(--qily-gk-dock-active-text)!important;background:var(--qily-gk-dock-hover)!important;border-color:var(--qily-gk-dock-gold)!important;box-shadow:inset 0 0 0 2px rgba(255,227,155,.72)!important,0 2px 7px rgba(7,60,71,.18)!important;transform:translateY(1px) scale(.97)!important}',
'html:root body #qilyGlobalKnowledgeDockSpacer{display:block!important;width:100%!important;height:88px!important;visibility:hidden!important;pointer-events:none!important}',
'#qilyGlobalKnowledgeSearchMask{position:fixed;inset:0;z-index:2147483000;display:none;align-items:flex-start;justify-content:center;padding:12vh 18px 30px;background:rgba(7,60,71,.56);backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px)}#qilyGlobalKnowledgeSearchMask.show{display:flex}#qilyGlobalKnowledgeSearchPanel{width:min(760px,100%);padding:20px;border:1px solid #d5e4e3;border-radius:12px;background:#fff;box-shadow:0 24px 70px rgba(7,60,71,.28)}#qilyGlobalKnowledgeSearchPanel h2{margin:0 0 12px;color:#0f4b5a;font-size:22px}#qilyGlobalKnowledgeSearchPanel input{width:100%;min-height:48px;padding:10px 13px;border:1px solid #b7d7d2;border-radius:8px;font:inherit}#qilyGlobalKnowledgeSearchResults{display:grid;gap:8px;max-height:46vh;margin-top:12px;overflow:auto}#qilyGlobalKnowledgeSearchResults a{display:block;padding:10px 12px;border:1px solid #d5e4e3;border-radius:8px;color:#0f4b5a;text-decoration:none;font-weight:800}#qilyGlobalKnowledgeSearchResults small{display:block;color:#526967;font-weight:500}#qilyGlobalKnowledgeSearchClose{margin-top:12px;padding:8px 12px;border:1px solid #0f4b5a;border-radius:7px;background:#0f4b5a;color:#fff;font-weight:800;cursor:pointer}',
'@media(max-width:820px){html:root body #floatDock.qily-page-action-nav{left:0!important;right:auto!important;bottom:0!important;width:100vw!important;max-width:100vw!important;grid-template-columns:repeat(7,minmax(0,1fr))!important;gap:4px!important;padding:5px 6px calc(5px + env(safe-area-inset-bottom))!important;border-width:1px 0 0!important;border-radius:0!important;box-shadow:0 -6px 22px rgba(15,75,90,.18)!important;overflow:visible!important;transform:none!important}html:root body #floatDock.qily-page-action-nav .qily-float-btn{min-height:54px!important;padding:6px 2px!important;border-radius:7px!important;font-size:11.5px!important;line-height:1.12!important}html:root body #floatDock .qily-dock-label>span{display:block!important}html:root body #qilyGlobalKnowledgeDockSpacer{height:calc(78px + env(safe-area-inset-bottom))!important}}',
'@media(max-width:390px){html:root body #floatDock.qily-page-action-nav{gap:3px!important;padding-left:4px!important;padding-right:4px!important}html:root body #floatDock.qily-page-action-nav .qily-float-btn{padding-left:1px!important;padding-right:1px!important;font-size:11px!important}}',
'@media(prefers-reduced-motion:reduce){html:root body #floatDock .qily-float-btn{transition:none!important}}@media print{#floatDock,#qilyGlobalKnowledgeDockSpacer,#qilyGlobalKnowledgeSearchMask{display:none!important}}'
].join('');(d.head||d.documentElement).appendChild(s);}
function parentRoute(){var p=location.pathname;if(p==='/global-knowledge/'||p==='/global-knowledge')return '/global-knowledge/';if(p.indexOf('/global-knowledge/view')===0)return '/global-knowledge/library/';return '/global-knowledge/';}
function labels(btn,action){var mobile=w.matchMedia&&w.matchMedia('(max-width:820px)').matches,lines=(mobile?MOBILE_LABELS:LABELS)[action]||[action];btn.innerHTML='';var box=d.createElement('span');box.className='qily-dock-label';lines.forEach(function(line){var row=d.createElement('span');row.textContent=line;box.appendChild(row)});btn.appendChild(box);btn.setAttribute('aria-label',lines.join(''));btn.title=lines.join('');}
function createDock(){var old=d.getElementById('floatDock');if(old)old.remove();var nav=d.createElement('nav');nav.id='floatDock';nav.className='qily-page-action-nav';nav.setAttribute('aria-label','Global Knowledge 页面快捷导航');ORDER.forEach(function(action){var b=d.createElement('button');b.type='button';b.className='qily-float-btn';b.dataset.action=action;labels(b,action);nav.appendChild(b)});d.body.appendChild(nav);var spacer=d.createElement('div');spacer.id='qilyGlobalKnowledgeDockSpacer';spacer.setAttribute('aria-hidden','true');d.body.appendChild(spacer);return nav;}
function copyText(text){if(navigator.clipboard&&navigator.clipboard.writeText)return navigator.clipboard.writeText(text);var t=d.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';d.body.appendChild(t);t.select();try{d.execCommand('copy')}catch(e){}t.remove();return Promise.resolve();}
function share(){if(navigator.share){navigator.share({title:d.title,url:location.href}).catch(function(){});return;}copyText(location.href).then(function(){w.alert('当前知识页面链接已复制。')});}
function searchUi(){var mask=d.getElementById('qilyGlobalKnowledgeSearchMask');if(mask)return mask;mask=d.createElement('div');mask.id='qilyGlobalKnowledgeSearchMask';mask.innerHTML='<div id="qilyGlobalKnowledgeSearchPanel" role="dialog" aria-modal="true" aria-label="本站知识搜索"><h2>本站知识搜索</h2><input id="qilyGlobalKnowledgeSearchInput" type="search" placeholder="搜索术语、精选简报或知识资料"><div id="qilyGlobalKnowledgeSearchResults"></div><button id="qilyGlobalKnowledgeSearchClose" type="button">关闭</button></div>';d.body.appendChild(mask);var input=mask.querySelector('input'),results=mask.querySelector('#qilyGlobalKnowledgeSearchResults'),cache=null;
function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})}
function build(){if(cache)return Promise.resolve(cache);return Promise.all([fetch('/qilylean/daily/index.json',{cache:'no-store'}).then(function(r){return r.ok?r.json():[]}).catch(function(){return []}),fetch('/knowledge/terminology.html',{cache:'no-store'}).then(function(r){return r.ok?r.text():''}).catch(function(){return ''}),fetch('/global-knowledge/library/',{cache:'no-store'}).then(function(r){return r.ok?r.text():''}).catch(function(){return ''})]).then(function(all){var list=[];(Array.isArray(all[0])?all[0]:[]).forEach(function(x){list.push({type:'精选简报',title:x.title||'',text:[x.title,x.summary,x.theme,x.date].join(' '),href:'/global-knowledge/briefs/?date='+encodeURIComponent(x.date||'')})});if(all[1]){var doc=new DOMParser().parseFromString(all[1],'text/html');doc.querySelectorAll('[data-term-card]').forEach(function(n){var code=(n.querySelector('.term-code')||{}).textContent||'',title=(n.querySelector('h3')||{}).textContent||code;list.push({type:'术语',title:(code?code+'｜':'')+title,text:n.textContent||'',href:'/global-knowledge/terminology/?q='+encodeURIComponent(code||title)})})}if(all[2]){var lib=new DOMParser().parseFromString(all[2],'text/html');lib.querySelectorAll('a.card[href^="/global-knowledge/"]').forEach(function(a){list.push({type:'知识资料',title:(a.querySelector('h3')||{}).textContent||'知识资料',text:a.textContent||'',href:a.getAttribute('href')})})}cache=list;return list;});}
function render(q){q=(q||'').trim().toLowerCase();if(!q){results.innerHTML='<small>输入关键词后搜索 Global Knowledge 隔离知识区。</small>';return;}results.innerHTML='<small>正在搜索……</small>';build().then(function(list){var hits=list.filter(function(x){return(x.text||'').toLowerCase().indexOf(q)>-1}).slice(0,30);results.innerHTML=hits.length?hits.map(function(x){return '<a href="'+esc(x.href)+'">'+esc(x.title)+'<small>'+esc(x.type)+'</small></a>'}).join(''):'<small>没有找到匹配知识内容。</small>';});}
input.addEventListener('input',function(){render(input.value)});mask.querySelector('#qilyGlobalKnowledgeSearchClose').addEventListener('click',function(){mask.classList.remove('show')});mask.addEventListener('click',function(e){if(e.target===mask)mask.classList.remove('show')});mask._qilyOpen=function(){mask.classList.add('show');setTimeout(function(){input.focus()},30)};return mask;}
function openSearch(){var local=d.querySelector('input[type="search"]');if(local&&d.activeElement!==local){local.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(function(){local.focus()},220);return;}var mask=searchUi();mask._qilyOpen();}
function act(action){if(action==='home'){location.href='/global-knowledge/';return}if(action==='top'){w.scrollTo({top:0,left:0,behavior:'smooth'});return}if(action==='back'){location.href=parentRoute();return}if(action==='previous'){if(history.length>1)history.back();else location.href=parentRoute();return}if(action==='search'){openSearch();return}if(action==='current'){share();return}if(action==='library'){location.href='/global-knowledge/library/';return}}
function init(){style();var dock=createDock();dock.addEventListener('click',function(e){var b=e.target.closest('button[data-action]');if(b)act(b.dataset.action)});w.addEventListener('resize',function(){dock.querySelectorAll('button[data-action]').forEach(function(b){labels(b,b.dataset.action)})},{passive:true});}
if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(document,window);
